from __future__ import annotations

from typing import Any, AsyncIterator, Protocol


class StoragePort(Protocol):
    async def initialize(self) -> None: ...
    async def ping(self) -> None: ...
    async def create_job(self, job: dict[str, Any]) -> None: ...
    async def save_job(self, job: dict[str, Any]) -> None: ...
    async def get_job(self, job_id: str) -> dict[str, Any] | None: ...
    async def list_jobs(self) -> list[dict[str, Any]]: ...
    async def is_job_deleted(self, job_id: str) -> bool: ...
    async def request_cancel(self, job_id: str) -> None: ...
    async def is_cancel_requested(self, job_id: str) -> bool: ...
    async def clear_cancel(self, job_id: str) -> None: ...
    async def delete_job(self, job_id: str) -> None: ...
    async def model_cost_summary(self, job_id: str) -> dict[str, Any]: ...
    async def list_recoverable_jobs(self) -> list[dict[str, Any]]: ...
    async def claim_job(self, job_id: str, worker_id: str, lease_seconds: int) -> bool: ...
    async def release_job(self, job_id: str, worker_id: str) -> None: ...
    async def record_model_call(self, record: dict[str, Any]) -> None: ...
    async def close(self) -> None: ...


class ModelGatewayPort(Protocol):
    def status(self) -> dict[str, Any]: ...
    def public_selection(self) -> dict[str, Any]: ...
    async def complete(self, purpose: str, messages: list[dict[str, Any]], *, stream: bool = False, max_tokens: int = 8000,
                       pinned_profile: dict | None = None, prompt_context: dict[str, Any] | None = None) -> str | AsyncIterator[str]: ...
    def pinned_state(self) -> dict[str, Any]: ...
    def assert_compatible(self, state: object) -> None: ...
